version: '3.6'

services:

  rest-api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    # image: sawtooth-rest-api-local:${ISOLATION_ID}
    volumes:
      - ./:/project/sawtooth-core
    container_name: rest-api
    ports:
      - "8008:8008"
    # depends_on:
    #   - validator
    command: |
      bash -c "
        bin/protogen
        cd rest_api/chilkat-linux
        python3 installChilkat.py
        cd ../
        python3 setup.py clean --all
        python3 setup.py build
        sawtooth-rest-api -v --bind rest-api:8008
      "
    stop_signal: SIGKILL