SOURCES = dxheap.c propogator.c dag.c throuhierarch.c \
dxvector.c dxatom.c dxmyltiarr.c dxlist.c dxqueue.c \
dxstack.c graphclass.c dxgraphserv.c preprocess.c preprocesscross.c \
preprocesstree.c protoio.c graphfromrel.c query.c reachhelper.c reachlabel.c \
allprint.c topo.c clusters.c timing.c

all:
	gcc -g -Wall $(SOURCES) -o prepro -lm
