version: '3.6'

services:

  bgx-rest-api:
    build:
      context: ../..
      dockerfile: bgx/rest-api/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgx-rest-api
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: bgx-rest-api
    networks:
    - network1
    ports:
      - "8002:8002"
    # depends_on:
    #   - validator
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/rest-api
        #cd chilkat-linux;
        #python3 installChilkat.py
        #cd ../
        python3 setup.py clean --all
        python3 setup.py build
        bgx-rest-api -vv --connect tcp://validator:4004 --bind bgx-rest-api:8002
      "
    stop_signal: SIGKILL

networks:
  network1:
     name: bgx-network
