# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BGX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Firebase'
pod 'Firebase/Messaging'

  #pod 'MSREventBridge', :path => '../node_modules/react-native-event-bridge'

  #pod 'RNShare', :path => '../node_modules/react-native-share'

  #pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  #pod 'RNLanguages', :path => '../node_modules/react-native-languages'

end