var ConfigAPI = {
    DOMAIN: "http://dev-demo1.softwareoutsource.org:8099",
    // DOMAIN: "http://192.168.1.70:8099",
    DOMAIN_IMAGE: "http://dev-demo1.softwareoutsource.org:8099/uploads/",
    DOMAIN_LINK: "http://dev-demo1.softwareoutsource.org:8088/",
    DOMAIN_IMAGE_MAGENTO: "http://dev-demo1.softwareoutsource.org:8088/pub/media/catalog/product/",
    // DOMAIN_IMAGE_MAGENTO: "http://192.168.1.242:8088/pub/media/catalog/product/",

    DOMAIN_BGT_WALLETS: "http://18.222.233.160:8008/wallets/",
    DOMAIN_NEWS_NOTIFICATIONS: "https://mvp.bgx.ai/twitter",

    TOKEN_LOCAL: "Bearer fc07kjwqr9knjq3y6nlyh4r31ddfr4x7",
    TOKEN_DEMO: "Bearer fc07kjwqr9knjq3y6nlyh4r31ddfr4x7",

    METHOD_LOGIN: "login",
    METHOD_UPDATE_PROFILE: "update_profile",
    METHOD_REGISTER: "register",
    METHOD_RESEND_ACTIVE_EMAIL: "resend_active_email",
    METHOD_GET_ADDRESS: "get_address",
    METHOD_GET_DIGITAL_SPOT: "get_digital_spot_list",
    METHOD_GET_ITEM_DETAIL: "get_item_detail",
    METHOD_GET_LIST_COMMENT: "get_list_comment",
    METHOD_LIST_CARD: "list_card",
    METHOD_LIST_CARD_TYPE: "list_card_type",
    METHOD_INTERFACE_CODE: "interface_code",
    METHOD_LIST_RATING: "list_rating",
    METHOD_ADD_TO_WISH_LIST: "add_to_wish_list",
    METHOD_DELETE_ITEM_FAVORITE: "delete_item_favorite",
    METHOD_CLEAR_ALL_FAVORITE: "clear_all_favorite",
    METHOD_GET_WISH_LIST: "get_wish_list",
    METHOD_COUNTRY_NAME: "country_name",
    METHOD_GET_ORDER_LIST: "get_order_list",
    METHOD_RESET_PASSWORD: "reset_password",
    METHOD_GET_LIST_CATEGORY: "get_list_category",
    METHOD_FILTER: "filter_by_category",
    METHOD_FILTER_MY_ORDER: "filter_my_order",
    METHOD_ADD_CARD: "add_card",
    METHOD_ADD_COMMENT: "add_comment",
    METHOD_CHECK_PRODUCT_IS_BOUGHT: "product_is_bought",
    METHOD_ADD_ITEM_SHOPPING_CART: "add_shopping_cart_item",
    METHOD_GET_LIST_SHOPPING_CART: "list_shopping_cart_item",
    METHOD_DELETE_SHOPPING_CART_ITEM: "delete_shopping_cart_item",
    METHOD_CLEAR_SHOPPING_CART: "clear_shopping_cart_item",
    METHOD_GET_LIST_PRODUCT_FILTERED: "get_list_product_filtered",
    METHOD_BGX_GET_BALANCE: "bgx_balance",
    METHOD_BGT_GET_BALANCE: "bgt_balance",
    METHOD_UPDATE_CARD: "update_card",
    METHOD_MAKE_TRANSACTION: "make_transaction",
    METHOD_COUNT_TWITTER: "count_twitter",
    METHOD_GET_LIST_IMAGE_MY_ORDER: "list_image_my_order",
    METHOD_GET_TRANSACTION_FEE: "get_transaction_fee",
    METHOD_SEND_EMAIL_RECEIPT: "send_payment_email",
    METHOD_CREATE_ORDER: "create_order",


    PARAM_METHOD: "method",
    PARAM_API_URL: "api_url",
    PARAM_LOCALE: "locale",
    PARAM_EMAIL: "email",
    PARAM_CURRENT_PASSWORD: "currentPassword",
    PARAM_PASSWORD: "password",
    PARAM_USERNAME: "username",
    PARAM_USER_ID: "userId",
    PARAM_PHONE: "phone",
    PARAM_ETHER_ADDRESS: "ethereumAddress",
    PARAM_BGX_ACCOUNT: "BGXAccount",
    PARAM_AVATAR: "avatar",
    PARAM_CODE: "code",
    PARAM_NOHASH: "noHash",
    PARAM_CUSTOMER_ID: "customer_id",
    PARAM_PRODUCT_ID: "productId",
    PARAM_CARDTYPEID: "cardTypeId",
    PARAM_TEMPLATE: "template",
    PARAM_CARDHOLDER: "cardHolder",
    PARAM_ISSUEDATE: "issueDate",
    PARAM_VALIDTILL: "validTill",
    PARAM_PIN: "PIN",
    PARAM_ADDRESS: "address",
    PARAM_PUBLICKEY: "publicKey",
    PARAM_PRIVATEKEY: "privateKey",
    PARAM_NICKNAME: "nickname",
    PARAM_TITLE: "title",
    PARAM_DETAIL: "detail",
    PARAM_RATING_VALUE: "ratingValue",
    PARAM_CUSTOMERID: "customerId",
    PARAM_STORE_ID: "storeId",
    PARAM_PUBLIC_KEY_HASHED: "public_key_hashed",
    PARAM_CARDID: "cardId",
    PARAM_ACTIVE: "active",
    PARAM_TOKEN: "token",
    PARAM_DEVICE_TYPE: "deviceType",
    PARAM_PAYLOAD: "payload",
    PARAM_TX_PAYLOAD: "tx_payload",
    PARAM_COIN_CODE: "coin_code",
    PARAM_SIGNED_PAYLOAD: "signed_payload",
    PARAM_ADDRESS_FROM: "address_from",
    PARAM_ADDRESS_TO: "address_to",
    PARAM_DATA: "data",
    PARAM_REASON: "reason",
    PARAM_BGT_ADDRESS: "bgtAddress",

    API_COUNTRY: "http://ip-api.com/json",
    API_GET_ADDRESS: "https://ico.bgx.ai//Api/GetUserInfo?email=tam.nguyen@titancorpvn.com&key=POsiK1wSTyvVGZh9euVM",
    API_GET_TRANSACTION: "http://api.etherscan.io/api?module=account&action=txlist&address=0x3693a830Cb17d4eA979E1e16D42F13f6B5e4C4Da&startblock=0&endblock=99999999&sort=desc&page=1&offset=10&apikey=POsiK1wSTyvVGZh9euVM",

    API_GET_DIGITAL_SPOT: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/products?searchCriteria=0",
    API_GET_ITEM_DETAIL: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/products/{sku}?searchCriteria=0",
    API_GET_LIST_COMMENT: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/review/reviews/{product_id}",
    API_GET_LIST_RATING: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/review/list/",
    API_ADD_TO_WISH_LIST: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/wishlist/add/",
    API_DELTE_ITEM_WISH_LIST: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/wishlist/delete/{wishlist_item_id}?customer_id={customer_id}",
    API_GET_WISH_LIST: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/wishlist/items?customer_id={customer_id}",
    API_GET_LIST_ORDER: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=customer_id&searchCriteria[filter_groups][0][filters][0][value]={customer_id}&searchCriteria[filter_groups][0][filters][0][condition_type]=eq",
    API_GET_LIST_CATEGORY: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/categories/list?searchCriteria[filter_groups][0][filters][0][field]=level&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][1][filters][0][field]=is_active&searchCriteria[filter_groups][1][filters][0][value]=1&searchCriteria[filter_groups][1][filters][0][condition_type]=eq",
    API_FILTER: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]={category_list}&searchCriteria[filter_groups][0][filters][0][condition_type]=in&searchCriteria[filter_groups][1][filters][0][field]=price&searchCriteria[filter_groups][1][filters][0][value]={price_from}&searchCriteria[filter_groups][1][filters][0][condition_type]=from&searchCriteria[filter_groups][2][filters][0][field]=price&searchCriteria[filter_groups][2][filters][0][value]={price_to}&searchCriteria[filter_groups][2][filters][0][condition_type]=to&searchCriteria[filter_groups][10][filters][0][field]=rating&searchCriteria[filter_groups][10][filters][0][value]={rating}&searchCriteria[filter_groups][10][filters][0][condition_type]=eq",
    API_FILTER_MY_ORDER: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/orders/self/{magento_id}?rating={rating}&category_id={category_list}&price={price_from},{price_to}",
    API_ADD_COMMENT: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/review/mine/post",
    API_CHECK_PRODUCT_IS_BOUGHT: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/orders/self/{customerId}/{productId}",
    API_GET_LIST_PRODUCT_FILTERED: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=entity_id&searchCriteria[filter_groups][0][filters][0][value]={string_product_id}&searchCriteria[filter_groups][0][filters][0][condition_type]=in",
    API_CREATE_ORDER: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/orders",
    API_GET_LIST_IMAGE_MY_ORDER: "http://dev-demo1.softwareoutsource.org:8088/rest/V1/products/media/list/{productList}",
    API_GLOBAL_TRANSACTIONS: "http://18.222.233.160:8008/global_transactions",


    // API_GET_DIGITAL_SPOT: "http://192.168.1.242:8088/rest/V1/products?searchCriteria=0",
    // API_GET_ITEM_DETAIL: "http://192.168.1.242:8088/rest/V1/products/{sku}?searchCriteria=0",
    // API_GET_LIST_COMMENT: "http://192.168.1.242:8088/rest/V1/review/reviews/{product_id}",
    // API_GET_LIST_RATING: "http://192.168.1.242:8088/rest/V1/review/list/",
    // API_ADD_TO_WISH_LIST: "http://192.168.1.242:8088/rest/V1/wishlist/add/",
    // API_DELTE_ITEM_WISH_LIST: "http://192.168.1.242:8088/rest/V1/wishlist/delete/{wishlist_item_id}?customer_id={customer_id}",
    // API_GET_WISH_LIST: "http://192.168.1.242:8088/rest/V1/wishlist/items?customer_id={customer_id}",
    // API_GET_LIST_ORDER: "http://192.168.1.242:8088/rest/V1/orders?searchCriteria[filter_groups][0][filters][0][field]=customer_id&searchCriteria[filter_groups][0][filters][0][value]={customer_id}&searchCriteria[filter_groups][0][filters][0][condition_type]=eq",
    // API_GET_LIST_CATEGORY: "http://192.168.1.242:8088/rest/V1/categories/list?searchCriteria[filter_groups][0][filters][0][field]=level&searchCriteria[filter_groups][0][filters][0][value]=1&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][1][filters][0][field]=is_active&searchCriteria[filter_groups][1][filters][0][value]=1&searchCriteria[filter_groups][1][filters][0][condition_type]=eq",
    // API_FILTER: "http://192.168.1.242:8088/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=category_id&searchCriteria[filter_groups][0][filters][0][value]={category_list}&searchCriteria[filter_groups][0][filters][0][condition_type]=in&searchCriteria[filter_groups][1][filters][0][field]=price&searchCriteria[filter_groups][1][filters][0][value]={price_from}&searchCriteria[filter_groups][1][filters][0][condition_type]=from&searchCriteria[filter_groups][2][filters][0][field]=price&searchCriteria[filter_groups][2][filters][0][value]={price_to}&searchCriteria[filter_groups][2][filters][0][condition_type]=to&searchCriteria[filter_groups][10][filters][0][field]=rating&searchCriteria[filter_groups][10][filters][0][value]={rating}&searchCriteria[filter_groups][10][filters][0][condition_type]=eq",
    // API_FILTER_MY_ORDER: "http://192.168.1.242:8088/rest/V1/orders/self/{magento_id}?rating={rating}&category_id={category_list}&price={price_from},{price_to}",
    // API_ADD_COMMENT: "http://192.168.1.242:8088/rest/V1/review/mine/post",
    // API_CHECK_PRODUCT_IS_BOUGHT: "http://192.168.1.242:8088/rest/V1/orders/self/{customerId}/{productId}",
    // API_GET_LIST_PRODUCT_FILTERED: "http://192.168.1.242:8088/rest/V1/products?searchCriteria[filter_groups][0][filters][0][field]=entity_id&searchCriteria[filter_groups][0][filters][0][value]={string_product_id}&searchCriteria[filter_groups][0][filters][0][condition_type]=in",
    // API_CREATE_ORDER: "http://192.168.1.242:8088/rest/V1/orders",
    // API_GET_LIST_IMAGE_MY_ORDER: "http://192.168.1.242:8088/rest/V1/products/media/list/{productList}",
    // API_GLOBAL_TRANSACTIONS: "http://18.222.233.160:8008/global_transactions",
    

    API_GET_BALANCE_BGT: "http://18.222.233.160:8008/wallets/{hasher_public_key}",
    API_MAKE_TRANSACTION: "http://18.222.233.160:8008/transactions",
    API_GET_TRANSACTION_FEE: "http://18.222.233.160:8008/fee",
    API_ADD_FUND: "http://18.222.233.160:8008/transactions/add_funds",

    IS_SHOW_ALERT: 0
};

module.exports = ConfigAPI;